skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
callpool = "ANMpzZvKMeGYBSCKsfg6u7eT1axDJuDSgbazDaXJ3WA7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
